# 项目相关配置
ruoyi:
  # 文件上传路径
  profile: D:/profile/

# 开发环境配置
server:
  # 服务端口
  port: 80

#数据源配置
spring:
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://118.25.47.126:3306/ry?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
        username: root
        password: P@ssw0rd
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password: